return {
	-- {
	-- 	"neovim/nvim-lspconfig",
	-- 	-- opts = function(_, opts)
	-- 	--     return vim.tbl_extend("force", opts, {
	-- 	--         servers = {
	-- 	--             lua_ls = { before_init = require("lazydev.lsp").before_init },
	-- 	--         },
	-- 	--     })
	-- 	-- end,
	-- 	-- config = function(_, opts)
	-- 	--     require("mason-lspconfig").setup_handlers({
	-- 	--         function(server)
	-- 	--             local server_status_ok, server_config = pcall(require, "langs." .. server)
	-- 	--             if not server_status_ok then
	-- 	--                 server_config = {}
	-- 	--             end
	-- 	--
	-- 	--             local config = vim.tbl_deep_extend("force", {
	-- 	--                 capabilities = require("utility.capabilities").capabilities,
	-- 	--                 on_attach = require("utility.on_attach").on_attach,
	-- 	--             }, server_config)
	-- 	--             require("lspconfig")[server].setup(config)
	-- 	--         end,
	-- 	--     })
	-- 	-- end,
	-- 	event = { "BufReadPre", "BufNewFile" },
	-- 	dependencies = {
	-- 		{ "saghen/blink.cmp" },
	-- 		{ "Issafalcon/lsp-overloads.nvim", event = "BufReadPre" },
	-- 		{
	-- 			"folke/lazydev.nvim",
	-- 			ft = "lua", -- only load on lua files
	-- 			dependencies = {
	-- 				{ "Bilal2453/luvit-meta", lazy = true }, -- optional `vim.uv` typings
	-- 			},
	-- 			opts = {
	-- 				library = {
	-- 					{ path = "luvit-meta/library", words = { "vim%.uv" } },
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- },
}
