return {
	-- "mason-org/mason.nvim",
	-- dependencies = {
	-- 	"mason-org/mason-lspconfig.nvim",
	-- 	"WhoIsSethDaniel/mason-tool-installer.nvim",
	-- },
	-- opts = {
	-- 	registries = {
	-- 		"github:mason-org/mason-registry",
	-- 		"github:Crashdummyy/mason-registry",
	-- 	},
	-- },
	-- config = function()
	-- 	require("mason").setup({
	-- 		registries = {
	-- 			"github:mason-org/mason-registry",
	-- 			"github:Crashdummyy/mason-registry",
	-- 		},
	-- 	})
	--
	-- 	-- list of servers for mason to install
	-- 	require("mason-lspconfig").setup({
	-- 		ensure_installed = {
	-- 			"lua_ls",
	-- 			"html",
	-- 			"cssls",
	-- 			"angularls",
	-- 			"eslint",
	-- 			"vtsls",
	-- 			"bashls",
	-- 			"yamlls",
	-- 			"jsonls",
	-- 			"marksman",
	-- 			"helm_ls",
	-- 			"dockerls",
	-- 			"docker_compose_language_service",
	-- 		},
	-- 	})
	--
	-- 	-- used for installing formatters and linters automatically
	-- 	require("mason-tool-installer").setup({
	-- 		ensure_installed = {
	-- 			"stylua", -- lua formatter
	-- 			"prettierd", -- js/ts formatter
	-- 			"eslint_d", -- js/ts linter
	-- 			"netcoredbg", -- .net debug adaptor
	-- 			"shfmt", -- bash formatter
	-- 			"roslyn",
	-- 		},
	-- 	})
	-- end,
}
